name: Uplas AI Agents CI

on:
  push:
    branches: [ main, develop ] # Or your primary branches
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10'] # Or your target Python versions

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install common dependencies (linters, pytest)
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-asyncio
        # Consider a shared dev-requirements.txt at root, or install per agent

    - name: Lint with flake8
      run: |
        # Lint all agent directories and shared_ai_libs
        flake8 personalized_tutor_nlp_llm/
        flake8 tts_agent/
        flake8 ttv_agent/
        flake8 project_generator_agent/
        flake8 nlp_content_agent/ # Assuming this new agent directory
        flake8 shared_ai_libs/
        # Add other directories as needed

    - name: Test with pytest
      run: |
        # Install dependencies for each agent before testing it
        # This is a simplified example; you might need a more robust way
        # to handle dependencies if they conflict or if tests are co-located.
        # Option 1: Install all requirements if they don't conflict
        # pip install -r personalized_tutor_nlp_llm/requirements.txt
        # pip install -r tts_agent/requirements.txt
        # ... etc. for all agents

        # Option 2: Run tests within each agent's context (might need adjustments to pytest invocation)
        echo "Testing Personalized AI Tutor..."
        pip install -r personalized_tutor_nlp_llm/requirements.txt
        pytest personalized_tutor_nlp_llm/

        echo "Testing TTS Agent..."
        pip install -r tts_agent/requirements.txt
        pytest tts_agent/

        echo "Testing TTV Agent..."
        pip install -r ttv_agent/requirements.txt
        pytest ttv_agent/

        echo "Testing Project Generation & Assessment Agent..."
        pip install -r project_generator_agent/requirements.txt
        pytest project_generator_agent/

        echo "Testing NLP Content Agent..."
        pip install -r nlp_content_agent/requirements.txt # Assuming creation of this agent
        pytest nlp_content_agent/
