name: Deploy All Uplas AI Agents

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - main # Or your main deployment branch, if deploying all on merge to main

jobs:
  deploy-nlp-content-agent:
    uses: ./.github/workflows/ai-agent-deploy-gcp.yml
    with:
      agent_name: 'nlp-content-agent'
      agent_directory: './nlp_content_agent' # Ensure this path is correct
      service_account_email: 'your-cloud-run-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
    secrets: inherit # Pass down secrets like GCP_SA_KEY, GCP_PROJECT_ID

  deploy-ai-tutor:
    uses: ./.github/workflows/ai-agent-deploy-gcp.yml
    needs: deploy-nlp-content-agent # Optional: define dependencies if order matters
    with:
      agent_name: 'ai-tutor-agent'
      agent_directory: './personalized_tutor_nlp_llm'
      service_account_email: 'your-cloud-run-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
      # Add specific environment variables for this agent here if needed
      # environment_variables: |
      #   LLM_MODEL_NAME=gemini-1.5-flash-001
      #   NLP_CONTENT_SERVICE_URL=https://nlp-content-agent-....run.app # Example
    secrets: inherit

  # ... Jobs for TTS, TTV, Project Generation & Assessment Agents ...

  # Example for Project Generator Agent
  deploy-project-generator:
    uses: ./.github/workflows/ai-agent-deploy-gcp.yml
    with:
      agent_name: 'project-generator-assessment-agent'
      agent_directory: './project_generator_agent'
      service_account_email: 'your-cloud-run-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
    secrets: inherit
